id              = affc-1900
source          = Meeus, Astronomical Formulae for Calculators, Ch.30
epoch.year      = 1900.0
epoch.jd        = 2415020.0

e.c0 = 1.0
e.c1 = -0.002495
e.c2 = -0.00000752

longitude.base = Lprime
longitude.trig = sin
latitude.base  = 0
latitude.trig  = sin
parallax.base  = 0.950724
parallax.trig  = cos

latitude.omega1 = 0.0004664
latitude.omega2 = 0.0000754
latitude.omega2.argConst = 275.05
latitude.omega2.argT = -2.30

accuracy.longitude.arcsec = 10
accuracy.latitude.arcsec  = 3
accuracy.parallax.arcsec  = 0.2

example.jd     = 2444214.5
example.lambda = 113.6604
example.beta   = -3.163672
example.pi     = 0.930249
